Vagrant.configure('2') do |config|
    config.vm.box = "ubuntu/precise64"

    config.vm.provider :virtualbox

    config.vm.provider :vmware_fusion do |fusion, override|
        # Standard Ubuntu image doesn't exist for VMWare
        override.vm.box = "hashicorp/precise64"
    end

    config.vm.define :vm1 do |vm1|
        vm1.vm.hostname = 'vm1'
    end

    config.vm.define :vm2 do |vm2|
        vm2.vm.hostname = 'vm2'
    end

end
