Vagrant.configure("2") do |config|

    config.vm.box     = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.provider :vmware_fusion do |fusion,override|
        override.vm.box     = "precise64_vmware_fusion"
        override.vm.box_url = "http://files.vagrantup.com/precise64_vmware_fusion.box"
    end

    config.vm.define :vm1 do |vm1|
        vm1.vm.hostname = 'vm1'
    end

    config.vm.define :vm2 do |vm2|
        vm2.vm.hostname = 'vm2'
    end

end
